### ISSUE TITLE
update_vital_articles.js可以每天處理多些條目嗎？

### ISSUE THREAD

**Issue by c933103** [kanasimi/wikibot#23]
現在英文維基Vital Articles應該有大概一千個條目的討論頁等待貼上相應分類標籤並且逐漸增加，但User:cewbot使用update_vital_articles.js現在每天只能在約十數個條目的討論頁貼上或更新相關模版，可以改善這處理數量嗎？

**Comment by kanasimi** [comment]
您是指從 [Vital articles update report](https://en.wikipedia.org/wiki/Wikipedia:Database_reports/Vital_articles_update_report) 看到的頁面清單嗎

**Comment by c933103** [comment]
> 您是指從 [Vital articles update report](https://en.wikipedia.org/wiki/Wikipedia:Database_reports/Vital_articles_update_report) 看到的頁面清單嗎? 最近一兩個月好像增加得很快...

是
有一部份增加是因為VA5快要填滿了，所以包括一些使用者在批量的把條目填進去想要完成VA5列表，但加了條目進去之後等bot來更新討論頁，結果就積壓起上來
