### ISSUE TITLE
Addition or removal of article to Vital Article Level 3 list have been mishandled by Cewbot

### ISSUE THREAD

**Issue by c933103** [kanasimi/wikibot#25]
Example situation 1: https://en.wikipedia.org/w/index.php?title=Wikipedia:Vital_articles/Level/5/Philosophy_and_religion&diff=prev&oldid=1076469648&diffmode=source After the article "Epistemology" have been downgraded from article 2 to article 3, the bot replaced the original description of ([[Wikipedia:Vital articles/Level/2|Level 2]]) with ([[Wikipedia:Vital articles/Level/2|Level 3]]), which make the Level *appears to be* correct, yet still link to the wrong, old level.

Example situation 2: https://en.wikipedia.org/w/index.php?title=Wikipedia:Vital_articles/Level/4/Society_and_social_sciences&diff=prev&oldid=1078450179&diffmode=source After some articles are removed from the Level 3 list, the bot failed to update their status on higher level lists, requiring manual intervention.

**Comment by c933103** [comment]
Also, the bot somehow added Level 4 label into Level 3 list. https://en.wikipedia.org/w/index.php?title=Wikipedia:Vital_articles&type=revision&diff=1080095338&oldid=1079986833&diffmode=source

**Comment by kanasimi** [comment]
Unable to reproduce the problem.
