### ISSUE TITLE
提报讨论版目录bug

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#30]
[这个版本中](https://zh.moegirl.org.cn/_?oldid=6370765)，「关于缘之空词条讨论区的部分内容折叠请求」被识别为了「已移动」，但实际情况是[「已存档」](https://zh.moegirl.org.cn/_?curid=392644#%E5%85%B3%E4%BA%8E%E7%BC%98%E4%B9%8B%E7%A9%BA%E8%AF%8D%E6%9D%A1%E8%AE%A8%E8%AE%BA%E5%8C%BA%E7%9A%84%E9%83%A8%E5%88%86%E5%86%85%E5%AE%B9%E5%8F%91%E8%B5%B7%E6%8A%95%E7%A5%A8%E6%88%96%E5%85%B6%E4%BB%96%E5%AF%BB%E6%B1%82%E5%85%B1%E8%AF%86%E6%96%B9%E6%B3%95%E7%9A%84%E9%97%AE%E9%A2%98%E4%B8%8E%E8%AF%B7%E6%B1%82)。
麻烦您检查了！

**Comment by kanasimi** [comment]
我這邊看到的是 “本主題全部或部分段落文字，已移動至 萌娘百科_talk:討論版/操作申請#關於緣之空詞條討論區的部分內容摺疊請求”?

**Comment by lovelyCARDINAL** [comment]
哦草，是我看错了，没问题了。
