### ISSUE TITLE
414 Request-URI Too Large

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#32]
萌娘百科这边的修复锚点的err日志中出现了大量414 Request-URI Too Large的报错
例如 `https://zh.moegirl.org.cn/api.php?pageids=210081%7C30839%7C31107%7C31159%7C31162%7C31165%7C31166%7C31176%7C31543%7C31544%7C31545%7C33137%7C33142%7C33144%7C33150%7C33158%7C33161%7C35787%7C35790%7C35800%7C37055%7C37110%7C37111%7C37138%7C37773%7C38170%7C40260%7C43093%7C43238%7C43241%7C43286%7C46196%7C46607%7C46993%7C47097%7C47138%7C47303%7C47547%7C48005%7C48015%7C48018%7C48024%7C48089%7C48219%7C48414%7C48452%7C49357%7C49366%7C49441%7C49499%7C49754%7C49889%7C49961%7C49981%7C50167%7C56125%7C56127%7C56806%7C56810%7C56816%7C56918%7C56920%7C56941%7C56987%7C58195%7C58198%7C58513%7C58517%7C59090%7C59938%7C59942%7C59992%7C61730%7C61852%7C62063%7C64088%7C64633%7C65046%7C65053%7C69468%7C69639%7C69643%7C69650%7C69689%7C69722%7C72727%7C72875%7C73276%7C73279%7C73281%7C75160%7C75169%7C75312%7C75322%7C77035%7C79998%7C80000%7C80003%7C80039%7C80045%7C80166%7C80365%7C80415%7C80417%7C80426%7C80441%7C80446%7C80470%7C80472%7C80474%7C80476%7C80479%7C80519%7C80521%7C80698%7C81447%7C81449%7C81474%7C81476%7C81782%7C81783%7C82348%7C82361%7C82429%7C82431%7C82456%7C82490%7C82514%7C82515%7C82517%7C82570%7C82653%7C82728%7C82731%7C82733%7C82896%7C82899%7C83179%7C83200%7C83218%7C83271%7C83272%7C83340%7C83341%7C83494%7C83569%7C83570%7C83580%7C83642%7C83664%7C83723%7C83852%7C83877%7C84296%7C84386%7C84614%7C84820%7C84874%7C85493%7C85497%7C85499%7C85667%7C85673%7C85686%7C85687%7C85690%7C88063%7C89514%7C89519%7C89715%7C89745%7C89747%7C89790%7C89818%7C89820%7C89910%7C89912%7C89915%7C90039%7C90264%7C90282%7C90366%7C90480%7C90512%7C90514%7C90545%7C90547%7C90549%7C90551%7C90658%7C90848%7C90849%7C90857%7C90859%7C90917%7C91105%7C91114%7C91166%7C91304%7C91307%7C91740%7C93178%7C93850%7C95853%7C96984%7C96988%7C97031%7C98115%7C98840%7C99458%7C99570%7C99793%7C100013%7C100230%7C100839%7C101195%7C101896%7C102421%7C102987%7C103591%7C103674%7C105108%7C105525%7C108670%7C108672%7C108674%7C110284%7C110337%7C110412%7C110437%7C110464%7C110529%7C110643%7C110774%7C110783%7C110820%7C110888%7C111216%7C111251%7C111311%7C111555%7C111669%7C111797%7C112505%7C112574%7C112649%7C112732%7C112740%7C112971%7C113211%7C113272%7C113400%7C114106%7C114147%7C114322%7C114337%7C114352%7C114790%7C114834%7C114920%7C115304%7C115306%7C115382%7C115384%7C115386%7C115389%7C116195%7C116417%7C116620%7C116919%7C116994%7C117280%7C117298%7C132113%7C141157%7C174979%7C178184%7C182337%7C184042%7C192415%7C200196%7C200425%7C200432%7C200447%7C200451%7C201684%7C201689%7C201691%7C201693%7C201775%7C201777%7C201779%7C201781%7C202528%7C210077%7C210117%7C218889%7C224567%7C252825%7C253719%7C253869%7C253877%7C253989%7C255713%7C257762%7C263948%7C264600%7C264814%7C267506%7C267940%7C268480%7C273002%7C291194%7C296302%7C300654%7C301354%7C301530%7C301942%7C302020%7C302026%7C303994%7C304780%7C308328%7C310390%7C311072%7C311306%7C311434%7C311500%7C311578%7C311610%7C313424%7C315798%7C315800%7C316560%7C318592%7C320434%7C320770%7C320772%7C321906%7C324964%7C325420%7C327336%7C334348%7C343352%7C344354%7C345892%7C346740%7C346940%7C348382%7C365632%7C366968%7C367626%7C370168%7C370186%7C370244%7C370284%7C370298%7C370338%7C383932%7C383934%7C384940%7C387956%7C387968%7C387974%7C402512%7C411136%7C417022%7C422891%7C423385%7C425076%7C425188%7C426073%7C427934%7C434872%7C435309%7C446378%7C446406%7C453883%7C454125%7C455910%7C456002%7C456005%7C456367%7C458333%7C460583%7C460900%7C467594%7C481475%7C482657%7C482889%7C482895%7C482943%7C483666%7C484279%7C484349%7C484856%7C485213%7C485238%7C485240%7C485483%7C485804%7C486120%7C486304%7C487496%7C490800%7C491252%7C491318%7C491735%7C491802%7C491977%7C492567%7C493424%7C493576%7C494967%7C495775%7C497102%7C497829%7C503235%7C503494%7C505997%7C508817%7C509340%7C509584%7C509910%7C514783%7C514946%7C518491%7C521806%7C523865%7C523985%7C524107%7C524168%7C524188%7C528056%7C530570%7C530952%7C531344%7C531871%7C532055%7C532797%7C532879%7C532969%7C533149%7C533226%7C533359%7C533877%7C533884%7C533895%7C534096%7C534689%7C534702%7C534815%7C535231%7C535234%7C535239%7C535251%7C535501%7C535544%7C535547%7C535569%7C535575%7C535650%7C536940%7C536949%7C536954%7C536961%7C536963%7C536967%7C536970%7C536974%7C536977%7C536980%7C536986%7C536990%7C537210%7C539214%7C539321%7C539327%7C31084%7C122910%7C122913&rvslots=main&rvprop=ids%7Ctimestamp%7Ccontent&prop=revisions&action=query&maxlag=5&format=json&utf8=1`
麻烦您检查了！
应该改成post就行

**Comment by kanasimi** [comment]
中文維基百科這邊似乎沒有問題，看起來似乎是萌娘百科這邊的設定?

**Comment by lovelyCARDINAL** [comment]
> 看起來似乎是萌娘百科這邊的設定?

可能是吧。get会出这个问题，post没问题。
