### ISSUE TITLE
关于Auto-archiver.js

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#33]
本想pull requests，但因不熟悉源代码还是改为issue
1、萌娘百科Auto-archiver只应在ns3执行，其他命名空间的存档暂时没有共识
2、存檔頁面標頭：萌娘百科不存在`{{Talk archive}}`，应使用[`{{用户存档页顶}}`](https://zh.moegirl.org.cn/_?curid=492957)
3、需要避免存档包含[`{{忍耐是有限的}}`](https://zh.moegirl.org.cn/_?curid=44512)的章节
4、另外想问下如果用户希望不存档指定章节，需要怎么做？

之前这个任务似乎只在您的个人讨论页执行，这回正式申请了一下，看看有更多用户使用。
麻烦您了！

**Comment by kanasimi** [comment]
1, 2: 本任務僅作用於嵌入{{[Auto-archive](https://zh.wikipedia.org/wiki/Template:Auto-archive)}}的頁面。欲引入此任務，建議複製{{[Auto-archive](https://zh.wikipedia.org/wiki/Template:Auto-archive)}}與[設定頁面](https://zh.wikipedia.org/wiki/User:Cewbot/log/20210429/configuration)。
3: 包含[{{忍耐是有限的}}](https://zh.moegirl.org.cn/_?curid=44512)的章節應該都在標頭?這樣的話應該不會被存檔。
4: 請參考 {{[Auto-archive](https://zh.wikipedia.org/wiki/Template:Auto-archive)}}

**Comment by lovelyCARDINAL** [comment]
1/2：说明文件我晚点弄一下
3：不一定，一般是某章节内部，仅需阻止存档该章节
4：新建{{不存档}}，内容为空应该没问题吧

**Comment by kanasimi** [comment]
請參考[設定頁面](https://zh.wikipedia.org/wiki/User:Cewbot/log/20210429/configuration)加入{{忍耐是有限的}}

**Comment by lovelyCARDINAL** [comment]
[设定页面](https://zh.moegirl.org.cn/_?curid=540092)已建立，麻烦您复核了！

其他我会晚点做。

**Comment by kanasimi** [comment]
大致沒什麼問題
接下來就看測試了
由於我沒有編輯權限
這些設定頁面您或許得參照維基計劃上面的更新

**Comment by lovelyCARDINAL** [comment]
> 這些設定頁面您或許得參照維基計劃上面的更新

了解！有变动可以在这里或者中文维基讨论页告知我，麻烦您了
