### ISSUE TITLE
关于字词转换处理

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#35]
1. 出现的多个[错误的处理](https://zh.moegirl.org.cn/_?diff=6513792)：H转换是隐藏的，直接去除-{H}-会导致文字被显示出来，应该去除包含文本在内整个转换规则。

2. 我注意到机器人会输出例如「在[[哥斯拉系列]]中使用了未登記的公共轉換組: "Show"」这一类的报错，能否让这个提示在条目讨论页发布？

**Comment by lovelyCARDINAL** [comment]
补充：发现一个[错误的移除](https://zh.moegirl.org.cn/index.php?oldid=6507349&diff=6513821)：移除这一条后会导致「怜」被转换为「憐」

**Comment by lovelyCARDINAL** [comment]
> 關於第二點需要個規範 例如創建個模板之類的 否則可能出現每次執行就添加一次的問題

已参考失效锚点建立了[Template:Invalid_CGroup](https://mzh.moegirl.org.cn/Template:Invalid_CGroup)

**Comment by kanasimi** [comment]
@lovelyCARDINAL 
您必須設定 no_registration_groups_template_name 為 `[[Template:Invalid CGroup]]`
另外這個功能沒測試過
所以得麻煩您測試之後再回報看有什麼需要修改的

**Comment by lovelyCARDINAL** [comment]
问题比较大
1. [丢失了zh-hant及之后的参数](https://zh.moegirl.org.cn/index.php?oldid=5954263&diff=6514351)
2. [自动加入了可能不需要的转换](https://zh.moegirl.org.cn/index.php?diff=prev&oldid=6514343)，疑似没有选定转换表版本为MW1.31所导致
3. 讨论页无法创建，被设定了nocreate。空页面无法parse，这可能直接导致了任务中止（？）
```
for_NoteTA_article: 在[[英雄联盟2018赛季全球总决赛对阵详情]]中使用了未登記的公共轉換組: "Games"
wiki_API.prototype.next: No page in the queue. You must run .page() first! 另請注意: 您不能在 callback 中呼叫 .edit() 之類的 wiki 函數！請在 callback 執行完畢後再執行新的 wiki 函數！例如放在 setTimeout() 中。
...
wiki_API_page: 不存在：[[Talk:英雄联盟2018赛季全球总决赛对阵详情]] 
```

**Comment by kanasimi** [comment]
請注意 我改了變數名稱 請參考
https://zh.wikipedia.org/wiki/User:Cewbot/log/20191129/configuration

**Comment by lovelyCARDINAL** [comment]
> 請注意 我改了變數名稱 請參考 https://zh.wikipedia.org/wiki/User:Cewbot/log/20191129/configuration

已修改✓
