### ISSUE TITLE
Broken anchors模板插入位置错误

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#37]
未插入在最开头，参见 [https://mzh.moegirl.org.cn/Special:Diff/6586152](https://mzh.moegirl.org.cn/Special:Diff/6586152)

**Comment by kanasimi** [comment]
討論頁一開頭就上來個{{反對}}也滿怪的?不如加個標題?

**Comment by lovelyCARDINAL** [comment]
> 討論頁一開頭就上來個{{反對}}也滿怪的

确实挺奇怪的（
不过我个人认为直接插入 prependtext 就可以避免这个问题？
