### ISSUE TITLE
Broken anchors识别问题

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#38]
如题，在[这个页面](https://mzh.moegirl.org.cn/index.php?title=Talk:%E6%98%8E%E6%97%A5%E6%96%B9%E8%88%9F/%E6%A2%97&action=history)多次提报有错误的「忍宗」和「无敌的小火龙」两个错误锚点，随后自动移除了模板。但事实上，这两个确实是不存在的锚点。
可能需要您这边检查问题所在。

**Comment by kanasimi** [comment]
好像不常出現。這恐怕得要長期觀察一下...

**Comment by lovelyCARDINAL** [comment]
又出现了同样的问题，参见[此处](https://mzh.moegirl.org.cn/index.php?title=Talk:%E6%98%8E%E6%97%A5%E6%96%B9%E8%88%9F/%E6%A2%97&action=history)

**Comment by kanasimi** [comment]
可能上次執行的還是舊的程式，還沒更新?麻煩請再觀察看看，謝謝。
