### ISSUE TITLE
讨论版更新问题

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#39]
萌娘百科的讨论版目录更新工作似乎暂停3天了，我这边看日志没找到具体问题，请问kanashimi佬能协助检查下么？

新年快乐！

**Comment by kanasimi** [comment]
異常 HTTP 狀態碼 429...

**Comment by lovelyCARDINAL** [comment]
现在toolforge的对外ip出口改变了么？我不清楚怎么测试。

**Comment by lovelyCARDINAL** [comment]
目前用户查核是查不到的……
我另外一个tool没有遇到429问题，应该就「mgp-cewbot」这个tool的出口ip变更了

**Comment by kanasimi** [comment]
我看了一下，執行時是 172.16.0.151 或 fe80::4cbc:5dff:fe43:e1c4，不確定CIDR要設多少。

**Comment by lovelyCARDINAL** [comment]
172.16开头的IPv4是局域网吧
萌娘百科不支持IPv6
