### ISSUE TITLE
锚点修复错误

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#40]
为正确的锚点添加了错误的空格
参见 https://mzh.moegirl.org.cn/index.php?oldid=6680608&diff=6680614

**Comment by lovelyCARDINAL** [comment]
似乎仍旧出现同样的问题
https://mzh.moegirl.org.cn/index.php?title=THE_IDOLM@STER_M@STERS_OF_IDOL_WORLD!!!!!2023&diff=prev&oldid=6708306

**Comment by kanasimi** [comment]
不容易debug…會顯示
異常 HTTP 狀態碼 429：https://mzh.moegirl.org.cn/api.php?assert=user&maxlag=5&format=json&utf8=1 
用維基百科測試的話,運作正常測不出來.

**Comment by lovelyCARDINAL** [comment]
我把mzh调成zh就可以了，非cronjob的出口IP 185.15.56.66 在mzh下没有waf豁免。

现在你应该能直接执行？方便再试试吗？
我试了下结果有点长，但是我没看到带空格的锚点

**Comment by kanasimi** [comment]
是的，這邊重新執行也正常。看不出問題發生在哪裡...

**Comment by lovelyCARDINAL** [comment]
emmmm 那再观察下看看
