### ISSUE TITLE
锚点修复疑似对Template:MultiAnchor误判

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#44]
[Module:MultiAnchor](https://mzh.moegirl.org.cn/%E6%A8%A1%E5%9D%97:MultiAnchor)

误判的页面：[Template_talk:Apex](https://mzh.moegirl.org.cn/index.php?title=Template_talk:Apex%E8%8B%B1%E9%9B%84)

**Comment by kanasimi** [comment]
機器人讀不懂lua，所以這部分程式碼還要修改測試。

**Comment by kanasimi** [comment]
做了點處置，若有問題請再回報。

**Comment by kanasimi** [comment]
@lovelyCARDINAL 麻煩在 Module:MultiAnchor, Template:MultiAnchor 幫忙掛上 {{Bot use warning}}

**Comment by lovelyCARDINAL** [comment]
> @lovelyCARDINAL 麻煩在 Module:MultiAnchor, Template:MultiAnchor 幫忙掛上 {{Bot use warning}}

done.
