### ISSUE TITLE
Pardon the response time !!!

### ISSUE THREAD

**Issue by BronkHonkyTonk** [kanasimi/wikibot#45]
Pardon the response time !!!
  /LLM /bot translation/editor to multiple platforms and languages 

_Originally posted by @BronkHonkyTonk in https://github.com/kanasimi/wikibot/issues/43#issuecomment-1591114202_

**Comment by BronkHonkyTonk** [comment]
Cyber security best practices

**Comment by kanasimi** [comment]
Perhaps you could describe in more detail what you would like to do?

**Comment by BronkHonkyTonk** [comment]
Resolves secritys black ends on back ends
