### ISSUE TITLE
Resolves secritys black ends on back ends

### ISSUE THREAD

**Issue by BronkHonkyTonk** [kanasimi/wikibot#47]
Wikii bot         Resolves secritys black  ends

_Originally posted by @BronkHonkyTonk in https://github.com/kanasimi/wikibot/issues/45#issuecomment-1612422152_

**Comment by kanasimi** [comment]
Can you point out where there is a "secritys" black ends problem?

**Comment by kanasimi** [comment]
Sorry I can't address this due to lack of information.
