### ISSUE TITLE
關於 重複字詞報告

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#48]
这个仓库没有discussion板块就只能发issue了

我想了解一下将转换目标不同的词列入重複字詞報告的缘由是什么？

例如：
（私隱）條例	4: [MediaWiki:Conversiontable/zh-cn](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-cn), [MediaWiki:Conversiontable/zh-my](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-my), [MediaWiki:Conversiontable/zh-sg](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-sg), [MediaWiki:Conversiontable/zh-tw](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-tw)

其中第4个（zh-tw）实际上与其他的转换目标不同，并不为同类项。

**Comment by kanasimi** [comment]
列出[[Wikipedia:字詞轉換處理/公共轉換組/重複字詞報告]]的用意是為了提醒某個詞彙列在哪些轉換表中。這樣若有需要改正，例如某個詞常見的名稱換了，就能一次改好，不會丟三落四。

**Comment by lovelyCARDINAL** [comment]
不过以上面的为例
如果要修改简体的转换，只需要修改[zh-cn](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-cn)、[zh-my](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-my)、[zh-sg](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-sg)，不一定需要修改[zh-tw](https://zh.wikipedia.org/wiki/MediaWiki:Conversiontable/zh-tw)，这实质上是两个不同的组。

**Comment by kanasimi** [comment]
舉例來說，若我們哪天想把`（私隱）條例`改成`（隱私）條例`，全部列出來的話就不會漏掉MediaWiki:Conversiontable/zh-tw。

**Comment by lovelyCARDINAL** [comment]
一般不会这么改吧，只会去改目标，不过理解了，谢谢！
