### ISSUE TITLE
Migrate cewbot from Toolforge GridEngine to Toolforge Kubernetes

### ISSUE THREAD

**Issue by lovelyCARDINAL** [kanasimi/wikibot#50]
[T319622](https://phabricator.wikimedia.org/T319622)
[T319890](https://phabricator.wikimedia.org/T319890)

**Comment by kanasimi** [comment]
https://phabricator.wikimedia.org/T350484

**Comment by lovelyCARDINAL** [comment]
请问我是否需要为mgp-cewbot申请更多的内存和CPU？如果要，一般申请多大，或者说您这边能否在[T350484](https://phabricator.wikimedia.org/T350484)下一并提及？

**Comment by kanasimi** [comment]
1. 需要，不過我準備先把當前的申請跑完再看看狀況。
2. 要用 webhooks 看起來要重寫一些程式碼，這邊還沒時間研究。您也可以參照著自己寫寫看?

**Comment by kanasimi** [comment]
https://phabricator.wikimedia.org/T353104
