### ISSUE TITLE
Incorrect entries from update_foreign_featured_contents_list.js

### ISSUE THREAD

**Issue by j824h** [kanasimi/wikibot#53]
In https://en.wikipedia.org/wiki/Wikipedia:Featured_articles_in_other_languages/Korean,
[분류:김규식](https://ko.wikipedia.org/wiki/%EB%B6%84%EB%A5%98:%EA%B9%80%EA%B7%9C%EC%8B%9D), [영빈 김씨](https://ko.wikipedia.org/wiki/%EC%98%81%EB%B9%88_%EA%B9%80%EC%94%A8) are not actually featured articles in Korean.

I am not sure how these get included by Cewbot.
Could this be a bug in the script?

Configuration: https://en.wikipedia.org/wiki/User:Cewbot/log/20210923/configuration
https://github.com/kanasimi/wikibot/blob/b5282a813b1d3b9e352df84376ad96051dfd275d/routine/20210923.update_foreign_featured_contents_list.js

**Comment by kanasimi** [comment]
I get the FA data from wikidata. You can see https://www.wikidata.org/wiki/Q7241948 , it's a FA...

**Comment by j824h** [comment]
I see. I'll fix the data in Wikidata. Thanks!
