### ISSUE TITLE
archive bot 泛用存檔機器人

### ISSUE THREAD

**Issue by kanasimi** [kanasimi/wikibot#8]
寫一個泛用存檔機器人

```
<!-- 以模板 Auto-archive section 指示存檔條件 討論頁面整體設定 -->
{{Auto-archive
<!-- 何時存檔 當達到特定條件時存檔 -->
| archive_after_last_comment = 最後討論日期開始，經過特定日數才存檔。 e.g., '7d', '7 days', '1w', '1 week', '1m', '1 month'
| archive_after_first_comment = TODO: 
| archive_at = TODO: %Y-%2m-%2d (timeout at exactly date 到達特定日期) || template:parameter (從某個模板的參數)

<!-- 存檔到哪裡 存檔到哪個子頁面 -->
| archive_to_subpage = Archive %1
| archive_to_subpage = Archive %Y-%2m
| archives_per_year = TODO?: 2, 3, 4 or 6, MUST using with archive_to_subpage like "%Y年%start_m月至%end_m月". For archive every quarter, set archives_per_year = 4.

<!-- 其他設定 -->
| config_template = template : parameter mapper (should write code manually) 從本議題(章節)中的哪個模板讀取存檔設定 包括何時存檔
| target_root_page = default is the page {{Auto-archive}} located in
<!--
for section_level = 3:
* 請每件申請各採用'''三級標題'''以方便存檔。機器人將會依各三級標題討論的最後發言時間各別存檔。
-->
| section_level = 2 <!-- 存檔章節級數 -->

| min_size_left = The record/discussion page will only be moved and archived if the characters exceeds this size. 紀錄/討論頁面字元數超過此大小(chars)才會被搬移存檔。
| min_size_to_create = The archive page will be created only if the characters exceeds this size. 字元數超過了這個長度，才會造出首個存檔。
| max_archive_page_size = If the characters of archive page exceeds this size (chars), move to the next archive page. 存檔頁面超過此大小(chars)就轉到下一個存檔頁面。
| max_archive_page_threads = 存檔頁面議題(章節)數超過此數值就轉到下一個存檔頁面。

| min_threads_left = 紀錄/討論頁面最少需要留下幾個議題(章節)，防止頁面被清空。
| min_threads_to_archive = 每次最少存檔幾個議題(章節)，可降低編輯頻率。

| archive_header = 存檔頁面標頭。未設定時預設為{{tl|Talk archive}}。
| left_link = {{Save to|%1}} {{Move to|%1}} After archiving, the topics will not be deleted directly, but the archive link will be kept. 存檔過後不直接刪除，而是保留存檔連結。
}}
```

* 將特定段落或者特定token轉移到指定頁面(日期或者序數)，並且移除原先頁面的內容、或保留特定連結
* 可結合 topic list
* [Talk page archiving bot updating incoming links](https://meta.wikimedia.org/wiki/Community_Wishlist_Survey_2021/Bots_and_gadgets#Talk_page_archiving_bot_updating_incoming_links) [[en:User:ClueBot_III#Keeping_linked)]]
* read {{en:Pin message}}, {{Do not archive|reason}} {{Do not archive|直到phabricator修復}}

e.g.,
https://zh.wikinews.org/wiki/Wikinews:%E8%8C%B6%E9%A6%86
https://ja.wikipedia.org/wiki/Wikipedia:Bot%E4%BD%9C%E6%A5%AD%E4%BE%9D%E9%A0%BC

* https://www.mediawiki.org/wiki/Manual:Pywikibot/archivebot.py https://gerrit.wikimedia.org/g/pywikibot/core/+/HEAD/scripts/archivebot.py
* https://en.wikipedia.org/wiki/User:MiszaBot/config
* https://en.wikipedia.org/wiki/User:Lowercase_sigmabot_III/Archive_HowTo
* https://en.wikipedia.org/wiki/User:ClueBot_III/ArchiveThis
* https://zh.wikipedia.org/wiki/User:Wcam/ArchiveConfig
* https://zh.wikipedia.org/wiki/User:Bluedeck/haystack/easy-archive
* https://www.wikidata.org/wiki/User:SpBot

also
* https://meta.wikimedia.org/wiki/Community_Wishlist_Survey_2021/Bots_and_gadgets#Bot_for_automatic_archiving_discussion

**Comment by kanasimi** [comment]
@hugolpz Hi. I want to use {{Auto-archive}} mentioned above to config archive operation. Can you provide some advice, especially on grammatical errors.

**Comment by hugolpz** [comment]
(I have low interenet access this week due to IRL projects. Back next week.)

**Comment by hugolpz** [comment]
(Being out of github/wikimedia projects for some times. Taking a wikibreak. Energy reloading. 👍)
